'use client'
import { useEffect, useState, useCallback } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Skeleton } from '@/components/ui/skeleton'
import { Input } from '@/components/ui/input'
import { EmptyState } from '@/components/shared'
import { toast } from 'sonner'
import {
  FileText,
  Download,
  Eye,
  Search,
  FileSignature,
  IdCard,
  ScrollText,
  Shield,
} from 'lucide-react'
import { fmtDate, docTypeLabel } from '../lib'

interface GenDoc {
  id: string
  docType: string
  title: string
  filePath: string | null
  metaJson: string | null
  generatedAt: string
  generatedBy: string | null
}

const DOC_ICONS: Record<string, any> = {
  offer_letter: FileSignature,
  appointment_letter: FileSignature,
  joining_letter: FileText,
  employment_agreement: ScrollText,
  nda: Shield,
  id_card: IdCard,
  salary_slip: FileText,
  experience_letter: ScrollText,
  relieving_letter: ScrollText,
}

export function Documents() {
  const [docs, setDocs] = useState<GenDoc[]>([])
  const [loading, setLoading] = useState(true)
  const [q, setQ] = useState('')

  const load = useCallback(async () => {
    setLoading(true)
    try {
      const res = await fetch('/api/employee/dashboard', { cache: 'no-store' })
      const json = await res.json()
      if (!res.ok) throw new Error(json.error || 'Failed')
      setDocs(json.employee?.generatedDocs || [])
    } catch (e: any) {
      toast.error(e.message || 'Failed to load documents')
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => { load() }, [load])

  const openDoc = (id: string) => {
    window.open(`/api/documents/${id}`, '_blank', 'noopener,noreferrer')
  }

  const filtered = docs.filter(d => {
    if (!q.trim()) return true
    const s = (d.title + ' ' + d.docType + ' ' + docTypeLabel(d.docType)).toLowerCase()
    return s.includes(q.toLowerCase())
  })

  if (loading) {
    return (
      <div className="space-y-6">
        <Skeleton className="h-12 w-full rounded-lg" />
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {Array.from({ length: 6 }).map((_, i) => <Skeleton key={i} className="h-32 w-full rounded-xl" />)}
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader className="pb-3">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <CardTitle className="flex items-center gap-2 text-base">
              <FileText className="h-4 w-4 text-[var(--gold)]" /> Generated Documents
            </CardTitle>
            <div className="relative w-full sm:w-64">
              <Search className="absolute left-2.5 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
              <Input
                value={q}
                onChange={e => setQ(e.target.value)}
                placeholder="Search documents…"
                className="pl-8"
              />
            </div>
          </div>
        </CardHeader>
        <CardContent>
          {filtered.length === 0 ? (
            <EmptyState
              icon={FileText}
              title={docs.length === 0 ? 'No documents yet' : 'No matching documents'}
              desc={docs.length === 0 ? 'Your official letters and certificates will appear here once generated by HR.' : 'Try a different search term.'}
            />
          ) : (
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {filtered.map((d) => {
                const Icon = DOC_ICONS[d.docType] || FileText
                return (
                  <div key={d.id} className="group flex flex-col rounded-xl border bg-card p-5 lift">
                    <div className="flex items-start justify-between">
                      <div className="grid h-11 w-11 place-items-center rounded-lg bg-[var(--navy)]/10 text-[var(--navy)] dark:bg-[var(--gold)]/15 dark:text-[var(--gold-light)]">
                        <Icon className="h-5 w-5" />
                      </div>
                      <span className="rounded-full border bg-muted/40 px-2 py-0.5 text-[10px] uppercase tracking-wider text-muted-foreground">
                        {docTypeLabel(d.docType)}
                      </span>
                    </div>
                    <div className="mt-3 flex-1">
                      <p className="text-sm font-semibold text-[var(--navy)] dark:text-white">{d.title}</p>
                      <p className="mt-1 text-xs text-muted-foreground">Generated {fmtDate(d.generatedAt)}</p>
                    </div>
                    <div className="mt-4 flex gap-2">
                      <Button size="sm" variant="outline" className="flex-1" onClick={() => openDoc(d.id)}>
                        <Eye className="mr-1.5 h-3.5 w-3.5" /> View
                      </Button>
                      <Button size="sm" className="flex-1 bg-[var(--navy)] hover:bg-[var(--navy-light)]" onClick={() => openDoc(d.id)}>
                        <Download className="mr-1.5 h-3.5 w-3.5" /> PDF
                      </Button>
                    </div>
                  </div>
                )
              })}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
